- name: Configure dnf
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Copy dnf config
      become: true
      ansible.builtin.copy:
        src: ./dnf.conf
        dest: /etc/dnf/dnf.conf

- name: Cleanup Packages
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Cleanup system by removing unwanted packages
      become: true
      ansible.builtin.dnf:
        name:
          - ghostscript
          - PackageKit-command-not-found
        state: absent

- name: Update packages
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Update installed Packages
      become: true
      ansible.builtin.dnf:
        name: '*'
        state: latest

- name: Remove Gnome
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Gather package facts to see if gnome is installed
      ansible.builtin.package_facts:
        manager: auto
    - name: Remove gnome-shell from protected packages
      become: true
      when: "'gnome-shell' in ansible_facts.packages"
      ansible.builtin.lineinfile:
        path: /etc/dnf/protected.d/fedora-workstation.conf
        search_string: "gnome-shell"
        state: absent
    - name: Remove all gnome packages
      become: true
      when: "'gnome-shell' in ansible_facts.packages"
      ansible.builtin.dnf:
        name: '*gnome*'
        state: absent
        
- name: Install DisplayManager
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install lightdm
      become: true
      ansible.builtin.dnf:
        name:
          - lightdm
          - light-locker
          - slick-greeter
        state: present

- name: Setup window manager
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Gather package facts to see if awesome is already installed
      ansible.builtin.package_facts:
        manager: auto
    - name: Install awesome window manager and dmenu
      become: true
      when: "'awesome' not in ansible_facts.packages"
      ansible.builtin.dnf:
        name: 
          - awesome
            lob
          - dmenu
        state: present
    - name: Copy awesome config
      when: "'awesome' not in ansible_facts.packages"
      ansible.builtin.copy:
        src: ./awesome
        dest: ~/.config/

- name: Install nerd font
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create font directory
      become: true
      register: dir
      ansible.builtin.file:
        path: /usr/share/fonts/Monaspace
        state: directory
    - name: Download and unpack font
      become: true
      when: dir.changed
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Monaspace.zip
        dest: /usr/share/fonts/Monaspace
        remote_src: true

- name: Setup terminal emulator
  hosts: localhost
  gather_facts: false
  tasks: 
    - name: Install kitty terminal
      become: true
      register: terminal
      ansible.builtin.dnf:
        name: kitty
        state: present
    - name: Copy kitty config
      when: terminal.changed
      ansible.builtin.copy:
        src: ./kitty.conf
        dest: ~/.config/kitty/

- name: Setup terminal multiplexer
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Enable zellij copr
      become: true
      community.general.copr:
        name: varlad/zellij
        state: enabled
    - name: Install zellij
      become: true
      register: zellij
      ansible.builtin.dnf:
        name: zellij
        state: present
    - name: Create config directory
      when: zellij.changed
      ansible.builtin.file:
        path: ~/.config/zellij
        state: directory
    - name: Copy zellij config
      when: zellij.changed
      ansible.builtin.copy:
        src: ./zellij.kdl
        dest: ~/.config/zellij/config.kdl

- name: Setup neovim
  hosts: localhost
  gather_facts: false
  task: 
    - name: Install neovim
      become: true
      register: nvim
      ansible.builtin.dnf:
        name: neovim
        state: present
    - name: Copy neovim config
      when: nvim.changed
      ansible.builtin.copy:
        src: ./nvim
        dest: ~/.config/






