- name: Configure dnf
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Copy dnf config
      become: true
      ansible.builtin.copy:
        src: ./dnf.conf
        dest: /etc/dnf/dnf.conf

- name: Cleanup Packages
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Cleanup system by removing unwanted packages
      become: true
      ansible.builtin.dnf:
        name:
          - ghostscript
          - PackageKit-command-not-found
        state: absent

- name: Update packages
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Update installed Packages
      become: true
      ansible.builtin.dnf:
        name: '*'
        state: latest

- name: Remove Gnome
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Gather package facts to see if gnome is installed
      ansible.builtin.package_facts:
        manager: auto

    - name: Remove gnome-shell from protected packages
      become: true
      when: "'gnome-shell' in ansible_facts.packages"
      ansible.builtin.lineinfile:
        path: /etc/dnf/protected.d/fedora-workstation.conf
        search_string: "gnome-shell"
        state: absent

    - name: Remove all gnome packages
      become: true
      when: "'gnome-shell' in ansible_facts.packages"
      ansible.builtin.dnf:
        name: '*gnome*'
        state: absent
        
- name: Install DisplayManager
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install lightdm
      become: true
      ansible.builtin.dnf:
        name:
          - lightdm
          - light-locker
          - slick-greeter
        state: present
